import PlanType from './planType';

import Entity from '@/shared/core/domain/Entity';
import UniqueEntityID from '@/shared/core/domain/UniqueEntityID';
import GenericErrors from '@/shared/core/logic/genericErrors';
import Guard from '@/shared/core/logic/guard';
import { PartialAutoGenerated } from '@/shared/types/common';

export interface IPlanProps extends PartialAutoGenerated {
  type: PlanType;
  price: number;
  description?: string;
  currency?: string;
}

export default class Plan extends Entity<IPlanProps> {
  constructor(props: IPlanProps, id?: UniqueEntityID) {
    super(props, id);
  }

  get id(): UniqueEntityID {
    return this._id;
  }

  get type(): PlanType {
    return this.props.type;
  }

  get description(): string {
    return this.props.description;
  }

  get price(): number {
    return this.props.price;
  }

  get currency(): string | undefined {
    return this.props.currency;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get deletedAt(): Date | undefined {
    return this.props.deletedAt;
  }

  public static create(props: IPlanProps, id?: UniqueEntityID) {
    const guardedProps = Guard.againstNullOrUndefinedBulk([
      { argument: props.type, argumentName: 'tipo de plano' },
      { argument: props.description, argumentName: 'descrição' },
      { argument: props.price, argumentName: 'preço' },
    ]);

    if (!guardedProps.succeeded) {
      throw new GenericErrors.InvalidParam(guardedProps.message);
    }

    const propsWithDefaults = {
      currency: 'BRL',
      ...props,
    };

    return new Plan(propsWithDefaults, id);
  }
}
