import PaymentIntegrator from './paymentIntegrator';
import PaymentStatus from './paymentStatus';

import Entity from '@/shared/core/domain/Entity';
import UniqueEntityID from '@/shared/core/domain/UniqueEntityID';
import GenericErrors from '@/shared/core/logic/genericErrors';
import Guard from '@/shared/core/logic/guard';
import { PaymentIntegratorEnum } from '@/shared/types';
import { PartialAutoGenerated } from '@/shared/types/common';

export interface IPaymentProps extends PartialAutoGenerated {
  planId: UniqueEntityID;
  /** @todo make this required if we have more than one integrator in the future*/
  integrator?: PaymentIntegrator;
  integratorId: string;
  status: PaymentStatus;
  amount: number;
  paymentUrl: string;
  currency?: string;
  paidAt?: Date;
}

export default class Payment extends Entity<IPaymentProps> {
  constructor(props: IPaymentProps, id?: UniqueEntityID) {
    super(props, id);
  }

  get id(): UniqueEntityID {
    return this._id;
  }

  get planId(): UniqueEntityID {
    return this.props.planId;
  }

  get integrator(): PaymentIntegrator {
    return this.props.integrator;
  }

  get integratorId(): string {
    return this.props.integratorId;
  }

  get status(): PaymentStatus {
    return this.props.status;
  }

  set status(status: PaymentStatus) {
    this.props.status = status;
  }

  get amount(): number {
    return this.props.amount;
  }

  get currency(): string | undefined {
    return this.props.currency;
  }

  get paidAt(): Date | undefined {
    return this.props.paidAt;
  }

  get paymentUrl(): string {
    return this.props.paymentUrl;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get deletedAt(): Date | undefined {
    return this.props.deletedAt;
  }

  public static create(props: IPaymentProps, id?: UniqueEntityID) {
    const guardedProps = Guard.againstNullOrUndefinedBulk([
      { argument: props.integratorId, argumentName: 'id do integrador' },
      { argument: props.planId, argumentName: 'id do plano' },
      { argument: props.status, argumentName: 'status' },
      { argument: props.amount, argumentName: 'valor' },
      { argument: props.paymentUrl, argumentName: 'url de pagamento' },
    ]);

    if (!guardedProps.succeeded) {
      throw new GenericErrors.InvalidParam(guardedProps.message);
    }

    const propsWithDefaults = {
      integrator: PaymentIntegrator.create(PaymentIntegratorEnum.STRIPE),
      currency: 'BRL',
      ...props,
    };

    return new Payment(propsWithDefaults, id);
  }
}
